version: '3.8'

services:
  sentry-redis:
    image: redis:6.2
    command: redis-server --maxmemory-policy noeviction
    volumes:
      - sentry-redis-data:/data
    restart: unless-stopped

  sentry-postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - sentry-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  sentry:
    image: getsentry/sentry:latest
    depends_on:
      - sentry-redis
      - sentry-postgres
    environment:
      SENTRY_SECRET_KEY: '${SENTRY_SECRET_KEY}'
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry-redis
    ports:
      - "9000:9000"
    volumes:
      - sentry-data:/var/lib/sentry/files
    restart: unless-stopped

  sentry-cron:
    image: getsentry/sentry:latest
    depends_on:
      - sentry-redis
      - sentry-postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: '${SENTRY_SECRET_KEY}'
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry-redis
    restart: unless-stopped

  sentry-worker:
    image: getsentry/sentry:latest
    depends_on:
      - sentry-redis
      - sentry-postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: '${SENTRY_SECRET_KEY}'
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry-redis
    restart: unless-stopped

volumes:
  sentry-redis-data:
  sentry-postgres-data:
  sentry-data: